In [1]:
import numpy as np

In [8]:
a = np.array((1, 2, 3.5, 4, 5))
a

array([1. , 2. , 3.5, 4. , 5. ])

In [3]:
a.dtype

dtype('int32')

In [7]:
a = np.array([1,2,3,4,5], dtype = np.float64)
a

array([1., 2., 3., 4., 5.])

In [9]:
a = a.astype (np.int32) 
a

array([1, 2, 3, 4, 5])

In [10]:
a.dtype

dtype('int32')

array = چند بعدی 

In [11]:
lst = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [12]:
b = np.array(lst, dtype = np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [14]:
b.dtype

dtype('float64')

In [15]:
b.ndim

2

In [16]:
b.shape

(2, 5)

In [17]:
b.size

10

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.empty((4,3))

array([[4.34288301e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 8.06632138e-308, 3.15625930e-033],
       [8.76150685e+169, 8.60957090e-043, 1.46317308e-047],
       [3.50370259e-033, 3.08737008e-057, 2.64947307e-032]])

In [22]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [24]:
np.random.standard_normal((2, 3))

array([[-1.39510789, -1.25176329,  0.56364269],
       [ 1.06945479,  0.99985131, -1.18057216]])

In [25]:
a = np.random.standard_normal((2, 3))
b = np.random.standard_normal((2, 3))

In [26]:
np.vstack([a, b])

array([[ 1.97886653, -0.80899927, -0.82077167],
       [-0.09752355,  1.76605783, -0.66256772],
       [-0.48775475,  1.29476977, -0.97091565],
       [-3.05658489, -1.42298989, -0.09648183]])

In [27]:
np.hstack([a, b])

array([[ 1.97886653, -0.80899927, -0.82077167, -0.48775475,  1.29476977,
        -0.97091565],
       [-0.09752355,  1.76605783, -0.66256772, -3.05658489, -1.42298989,
        -0.09648183]])

In [28]:
a.transpose()

array([[ 1.97886653, -0.09752355],
       [-0.80899927,  1.76605783],
       [-0.82077167, -0.66256772]])

In [29]:
a.T

array([[ 1.97886653, -0.09752355],
       [-0.80899927,  1.76605783],
       [-0.82077167, -0.66256772]])

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [31]:
a = np.array([1, 2, 3, 4])
a.shape, a

((4,), array([1, 2, 3, 4]))

In [33]:
b = a.T
b.shape

(4,)

In [34]:
a == b

array([ True,  True,  True,  True])

In [35]:
np.all (b == a)

True

In [36]:
a = np.array([[1, 2, 3, 4]])
a.shape, a

((1, 4), array([[1, 2, 3, 4]]))

In [37]:
b = a.T
b.shape

(4, 1)

In [38]:
np.all (b == a)

False

In [39]:
v = np.linspace(0, 10, 5)
v + 1

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [40]:
ones = np.ones((6,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
twos = np.ones((6,1)) * 2 
twos

array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.]])

In [45]:
twos = np.ones((6,2)) * 2 
twos

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [44]:
ones + twos

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [46]:
x = np.linspace(0,100,10000000)

In [47]:
x.size

10000000

In [48]:
import math 
def get_lst(x):
    lst = []
    for i in x:
        lst.append(math.sin(i))
    return lst    

In [49]:
%timeit get_lst(x)

4.08 s ± 201 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [50]:
%timeit np.sin(x)

167 ms ± 6.28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [52]:
4.08 / 0.0167 

244.311377245509